name: Aqua Security Scan
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  AQUA_KEY: ${{ secrets.AQUA_KEY }}
  AQUA_SECRET: ${{ secrets.AQUA_SECRET }}

jobs:
  supply-chain-scan:
    name: Supply Chain (Code)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Aqua Supply Chain Scanner
        run: |
          docker run \
            -e AQUA_KEY \
            -e AQUA_SECRET \
            -e TRIVY_RUN_AS_PLUGIN=aqua \
            -v $(pwd):/scanning \
            --entrypoint sh \
            aquasec/trivy:latest \
            -c "git config --global safe.directory /scanning && trivy fs --scanners vuln,secret,misconfig --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL /scanning"

  image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Aqua Image Scanner
        run: |
          docker run \
            -e AQUA_KEY \
            -e AQUA_SECRET \
            -e TRIVY_RUN_AS_PLUGIN=aqua \
            aquasec/trivy:latest \
            image --scanners vuln,secret,misconfig \
                  --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
                  crapi/crapi:latest
